//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceWatcher.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public long ID { get; set; }
        public Nullable<long> ProductRetailerID { get; set; }
        public double Value { get; set; }
        public string Timestamp { get; set; }
    
        public virtual ProductRetailer ProductRetailer { get; set; }
    }
}
