//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceWatcher.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRetailer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductRetailer()
        {
            this.Prices = new HashSet<Price>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<long> RetailerID { get; set; }
        public string UrlTail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Prices { get; set; }
        public virtual Product Product { get; set; }
        public virtual Retailer Retailer { get; set; }
    }
}
